name: Release_Redmi-AX6 plus（imm） 
run-name: Release - ${{ inputs.model || 'RedMi-AX6_plus_imm'}}

on:
  workflow_dispatch:
    inputs:
      model:
        required: true
        description: Device Model
        type: choice
        default: RedMi-AX6_plus_imm
        options:
          #- aliyun_ap8220_immwrt
          #- cmcc_rax3000m_immwrt
          #- jdcloud_ax6000_immwrt
          #- jdcloud_ipq60xx_immwrt
          #- jdcloud_ipq60xx_libwrt
          #- n1_immwrt
          #- redmi_ax5_immwrt
          - RedMi-AX6_plus_imm
          - RedMi-AX6_plus_libwrt
          #- redmi_ax6000_immwrt21
          #- zn_m2_immwrt
          #- zn_m2_libwrt
          #- x64_immwrt


  schedule:
    - cron: 43 3 * * 4

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DIY_my_SH: sh/ax6_imm_diy-part2.sh

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: 可用磁盘空间
        uses: sbwml/actions@free-disk

      - name: 构建系统设置
        run: |
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E apt -yqq install dos2unix
          sudo -E apt -yqq install libfuse-dev
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E systemctl daemon-reload

      - name: 检出
        uses: actions/checkout@v4

      - name: 设置构建日期和时区
        run: |
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          export BUILD_SRC=$(awk -F"=" '/REPO_URL/ {print $NF}' "./compilecfg/${{ inputs.model || 'RedMi-AX6_plus_imm'}}.ini")
          echo "BUILD_SRC=$BUILD_SRC" >> $GITHUB_ENV

      - name: 克隆固件代码
        run: ./sh/pre_clone_action.sh ${{ inputs.model || 'RedMi-AX6_plus_imm'}}

      - name: 缓存依赖
        uses: actions/cache@v4
        with:
          path: |
            ./action_build/.ccache
            ./action_build/staging_dir
          key: ${{ matrix.os }}-${{ hashFiles('**/repo_flag') }}-${{ env.BUILD_DATE }}
          restore-keys: |
            ${{ matrix.os }}-${{ hashFiles('**/repo_flag') }}-

      - name: 刷新缓存
        run: |
          if [ -d "./action_build/staging_dir" ]; then
            find "./action_build/staging_dir" -type d -name "stamp" -not -path "*target*" | while read -r dir; do
                find "$dir" -type f -exec touch {} +
            done
          fi

      - name: 构建固件
        run: |
          sed -i 's|update_lucky|#update_lucky|g' sh/update.sh
          chmod +x $DIY_my_SH
          sed -i "/\$BASE_PATH\/sh\/update\.sh/a $GITHUB_WORKSPACE/$DIY_my_SH" sh/build.sh
          ./sh/build.sh ${{ inputs.model || 'RedMi-AX6_plus_imm'}}


      - name: 获取内核版本
        run: |
          # 获取内核版本
          echo "KVER=$(find ./action_build/dl -maxdepth 1 -name "linux-[4-6]\.*" | sort -r | head -n 1 | grep -oE "[4-6]\.[0-9]{1,3}\.[0-9]{1,3}")" >> $GITHUB_ENV
          #获取最近更新内容
          cd action_build
          useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H")
          echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
          cd ..
          
      - name: 删除旧缓存
        run: |
          # 获取缓存列表并删除
          gh cache list --key ${{ matrix.os }}-${{ hashFiles('**/repo_flag') }}- --json key --jq '.[] | .key' | while read -r key; do
            gh cache delete "$key"
          done
          # 输出缓存状态
          echo "========cache status========"
          echo "ccache: $(du -sh ./action_build/.ccache | cut -f 1)"
          echo "staging: $(du -sh ./action_build/staging_dir | cut -f 1)"

      - name: 输出虚拟机信息
        run: |
          echo "=============================================="
          lscpu | grep -E "name|Core|Thread"
          echo "=============================================="
          df -h
          echo "=============================================="

      - name: 封装OpenWrt固件
        if: ${{ inputs.model == 'n1_immwrt' }}
        uses: unifreq/openwrt_packit@master
        env:
          OPENWRT_ARMVIRT: firmware/*.tar.gz
          PACKAGE_SOC: s905d
          KERNEL_VERSION_NAME: 6.6.y
          WHOAMI: fichen

      - name: 准备发布简介
        run: |
          echo "云编译发布" > release_body.txt
          echo "源码：${{ env.BUILD_SRC }}" >> release_body.txt
          echo "Kernel: ${{ env.KVER }}" >> release_body.txt
          echo "WIFI密码: 12345678" >> release_body.txt
          echo "LAN地址: 192.168.123.1" >> release_body.txt
          echo "源码最近提交信息:" >> release_body.txt
          echo "${{ env.useVersionInfo }}" >> release_body.txt
          echo "插件：" >> release_body.txt
          echo "$(grep -oP "luci-app(-[a-zA-Z0-9]{1,}){1,}" ./firmware/*.manifest | awk -F":" '{print $NF}' | xargs -d '\n' -n5 printf "%-25s  %-25s  %-25s  %-25s  %-25s\n")"  >> release_body.txt


      - name: 发布固件
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_DATE }}_${{ inputs.model || 'RedMi-AX6_plus_imm'}}
          files: ${{ inputs.model == 'n1_immwrt' && env.PACKAGED_OUTPUTPATH || './firmware' }}/*.*
          body_path: ./release_body.txt

      - name: 删除旧的工作流和固件
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: Release_Redmi-AX6 plus（imm）
          retain_days: 20
          keep_minimum_runs: 5
    
      - name: 删除旧的发布版本
        uses: codesnas/delete-older-releases@main
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          #repo:
          keep_latest: 5
          delete_tag_pattern: ${{ inputs.model || 'RedMi-AX6_plus_imm'}}
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}